# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

theta_ml <- function(theta, y, mu, weights) {
    .Call('_scZINB_theta_ml', PACKAGE = 'scZINB', theta, y, mu, weights)
}

updateEM <- function(y, betas, offsetx, gammas, offsetz, X, theta, lambda, tau, irlsConv, betaWeights, gammaWeights, maxIT, loud, eps, model, penType, maxIT2) {
    .Call('_scZINB_updateEM', PACKAGE = 'scZINB', y, betas, offsetx, gammas, offsetz, X, theta, lambda, tau, irlsConv, betaWeights, gammaWeights, maxIT, loud, eps, model, penType, maxIT2)
}

updateEM2 <- function(y, betas, offsetx, gammas, offsetz, X, theta, lambda, tau, irlsConv, betaWeights, gammaWeights, maxIT, loud, eps, penType) {
    .Call('_scZINB_updateEM2', PACKAGE = 'scZINB', y, betas, offsetx, gammas, offsetz, X, theta, lambda, tau, irlsConv, betaWeights, gammaWeights, maxIT, loud, eps, penType)
}

